import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import AuthProvider from '@/modules/auth_provider';
import WebSocketProvider from '@/modules/ws_provider';
import Header from '@/components/Header';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chat app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <WebSocketProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="flex flex-col h-full min-h-screen"><Header/>{children}</div>
          </body>
        </html>
      </WebSocketProvider>
    </AuthProvider>
  );
}
